### ISSUE TITLE
Db variable not found

### ISSUE THREAD

**Issue by Hum4n01d** [Shexplore/shexplore-server#1]
Not sure what happened. Here is the error:

```
shexplore-server/models/account.js:10
var User = db.Model.extend({ tableName: 'users' }, {
           ^

ReferenceError: db is not defined
    at Object.<anonymous> (shexplore-server/models/account.js:10:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (shexplore-server/routes/users.js:6:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

```

@pfgithub, do you know what is going on here?

**Comment by pfgithub** [comment]
The DB wasn't initialized right. For a temporary fix, remove anything
requiring those files

**Comment by lakshaym30** [comment]
Which files was DB used in?

Sincerely,

Lakshay Maharana
Miller Leadership 2015-2016

**Comment by Hum4n01d** [comment]
@FlyKnight, the file is shexplore-server/models/account.js. At least that’s the file that had an error.

**Comment by lakshaym30** [comment]
That file isn't there right now.

Sincerely,

Lakshay Maharana
Miller Leadership 2015-2016

**Comment by Hum4n01d** [comment]
Are you sure? Try git pulling. It's on the repo.

**Comment by Hum4n01d** [comment]
Solved
